-- LinkYouth — Catalogo de tags (RF2.3.1: lista predefinida de donde elegir).
-- Es idempotente: se puede correr las veces que haga falta.

insert into tags (slug, nombre, categoria) values
  ('react',              'React',                'tecnologia'),
  ('typescript',         'TypeScript',           'tecnologia'),
  ('javascript',         'JavaScript',           'tecnologia'),
  ('nextjs',             'Next.js',              'tecnologia'),
  ('nodejs',             'Node.js',              'tecnologia'),
  ('python',             'Python',               'tecnologia'),
  ('java',               'Java',                 'tecnologia'),
  ('sql',                'SQL',                  'tecnologia'),
  ('git',                'Git',                  'tecnologia'),
  ('rest-apis',          'REST APIs',            'tecnologia'),
  ('testing',            'Testing automatizado', 'tecnologia'),
  ('tailwind',           'Tailwind CSS',         'diseno'),
  ('html-css',           'HTML y CSS',           'diseno'),
  ('figma',              'Figma',                'diseno'),
  ('diseno-ui',          'Diseno de interfaces', 'diseno'),
  ('accesibilidad',      'Accesibilidad web',    'diseno'),
  ('analisis-datos',     'Analisis de datos',    'datos'),
  ('excel',              'Planillas de calculo', 'datos'),
  ('power-bi',           'Power BI',             'datos'),
  ('estadistica',        'Estadistica',          'datos'),
  ('atencion-cliente',   'Atencion al cliente',  'negocios'),
  ('marketing-digital',  'Marketing digital',    'negocios'),
  ('ventas',             'Ventas',               'negocios'),
  ('gestion-proyectos',  'Gestion de proyectos', 'negocios'),
  ('administracion',     'Administracion',       'negocios'),
  ('ingles-b2',          'Ingles B2',            'idiomas'),
  ('ingles-c1',          'Ingles C1',            'idiomas'),
  ('portugues',          'Portugues',            'idiomas'),
  ('trabajo-en-equipo',  'Trabajo en equipo',    'habilidades_blandas'),
  ('comunicacion',       'Comunicacion',         'habilidades_blandas'),
  ('resolucion-problemas', 'Resolucion de problemas', 'habilidades_blandas'),
  ('autonomia',          'Autonomia',            'habilidades_blandas'),
  ('adaptabilidad',      'Adaptabilidad',        'habilidades_blandas')
on conflict (slug) do update
  set nombre = excluded.nombre,
      categoria = excluded.categoria;
